{% set version = '0.4.1' %}

package:
  name: r-cpp11armadillo
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/cpp11armadillo_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/cpp11armadillo/cpp11armadillo_{{ version }}.tar.gz
  sha256: 826b8b0bb255b454704280cca34fe3720e2dc6ff39babd700609fbad3449d043

build:
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - r-cpp11
  run:
    - r-base
    - r-cpp11

test:
  commands:
    - $R -e "library('cpp11armadillo')"           # [not win]
    - "\"%R%\" -e \"library('cpp11armadillo')\""  # [win]

about:
  home: https://pacha.dev/cpp11armadillo/
  dev_url: https://github.com/pachadotdev/cpp11armadillo
  license: Apache-2.0
  license_file: LICENSE.md
  summary: Provides function declarations and inline function definitions that facilitate communication
    between R and the 'Armadillo' 'C++' library for linear algebra and scientific computing.
    This implementation is detailed in Vargas Sepulveda and Schneider Malamud (2024)
    <doi:10.48550/arXiv.2408.11074>.

extra:
  recipe-maintainers:
    - conda-forge/r

# The original CRAN metadata for this package was:

# Package: cpp11armadillo
# Type: Package
# Title: An 'Armadillo' Interface
# Description: Provides function declarations and inline function definitions that facilitate communication between R and the 'Armadillo' 'C++' library for linear algebra and scientific computing. This implementation is detailed in Vargas Sepulveda and Schneider Malamud (2024) <doi:10.48550/arXiv.2408.11074>.
# Version: 0.4.1
# Authors@R: c( person( given = "Mauricio", family = "Vargas Sepulveda", role = c("aut", "cre"), email = "m.sepulveda@mail.utoronto.ca", comment = c(ORCID = "0000-0003-1017-7574")), person( given = "Jonathan", family = "Schneider Malamud", role = c("ctb")), person( given = "Conrad", family = "Sanderson", role = c("aut"), comment = "Armadillo library (C++)") )
# Imports: cpp11
# Suggests: desc, knitr, mockery, rmarkdown, testthat (>= 3.0.0), withr
# Depends: R(>= 3.5.0)
# License: Apache License (>= 2)
# BugReports: https://github.com/pachadotdev/cpp11armadillo/issues
# URL: https://pacha.dev/cpp11armadillo/, https://github.com/pachadotdev/cpp11armadillo
# RoxygenNote: 7.3.2
# Encoding: UTF-8
# VignetteBuilder: knitr
# Config/testthat/edition: 3
# NeedsCompilation: no
# Packaged: 2024-12-18 08:22:11 UTC; pacha
# Author: Mauricio Vargas Sepulveda [aut, cre] (<https://orcid.org/0000-0003-1017-7574>), Jonathan Schneider Malamud [ctb], Conrad Sanderson [aut] (Armadillo library (C++))
# Maintainer: Mauricio Vargas Sepulveda <m.sepulveda@mail.utoronto.ca>
# Repository: CRAN
# Date/Publication: 2024-12-19 17:00:02 UTC
